"""initial schema

Revision ID: 0cc324ff126b
Revises: 
Create Date: 2026-09-14 19:28:46.655531

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cc324ff126b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('normalized_first_name', sa.String(), nullable=False),
    sa.Column('normalized_last_name', sa.String(), nullable=False),
    sa.Column('normalized_address', sa.String(), nullable=False),
    sa.Column('normalized_phone_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_normalized_address'), 'customers', ['normalized_address'], unique=False)
    op.create_index(op.f('ix_customers_normalized_first_name'), 'customers', ['normalized_first_name'], unique=False)
    op.create_index(op.f('ix_customers_normalized_last_name'), 'customers', ['normalized_last_name'], unique=False)
    op.create_index(op.f('ix_customers_normalized_phone_number'), 'customers', ['normalized_phone_number'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('pending_customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.Enum('anonymous', 'collecting_identity', 'code_sent', 'awaiting_code', 'verified', 'escalated_to_human', name='session_state'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_to_human_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_agent_name', sa.String(), nullable=True),
    sa.Column('pending_first_name', sa.String(), nullable=True),
    sa.Column('pending_last_name', sa.String(), nullable=True),
    sa.Column('pending_address', sa.String(), nullable=True),
    sa.Column('pending_phone_number', sa.String(), nullable=True),
    sa.Column('code_hash', sa.String(), nullable=True),
    sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code_attempts', sa.Integer(), nullable=False),
    sa.Column('code_max_attempts', sa.Integer(), nullable=False),
    sa.Column('code_last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['pending_customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_session_token'), 'chat_sessions', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_session_token'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_customers_normalized_phone_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_normalized_last_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_normalized_first_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_normalized_address'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
