"""shipments and packages

Section 4.4 / ERD 6.4: shipments (FK customers RESTRICT, status enum with 5 values, unique tracking number)
and packages (FK shipments ON DELETE CASCADE).

Revision ID: 357af0a384f5
Revises: 0cc324ff126b
Create Date: 2026-10-02 12:47:06.045808

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '357af0a384f5'
down_revision: str | None = '0cc324ff126b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('tracking_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('label_created', 'in_transit', 'out_for_delivery', 'delivered', 'exception', name='shipment_status'), nullable=False),
    sa.Column('carrier', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('estimated_delivery', sa.Date(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_index(op.f('ix_shipments_customer_id'), 'shipments', ['customer_id'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('declared_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_shipment_id'), 'packages', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_shipment_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_shipments_customer_id'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
    # autogenerate does not drop the native enum type - without this a later upgrade would fail on "type already exists"
    sa.Enum(name='shipment_status').drop(op.get_bind(), checkfirst=True)
